### ISSUE TITLE
Raster Calculations in Python additional line needed in example

### ISSUE THREAD

**Issue by klange77** [carpentries-incubator/geospatial-python#109]
Hello there! I have discovered in issue in the Raster Calculations in Python lesson under the "Classifying Continuous Rasters in Python" Section. In the first example where the lesson directs to create the Classified Canopy Height Model- NEON Harvard Forest Field Site graph, the code block under #Defines the bins for pixel values calls for np.inf. However, the lesson does not have the learner import numpy as np at the top of this code block. 

`import numpy as np` should be added where other packages are imported so the code block can be run successfully. 

Additionally, under #Making the plot "Classfied" is spelt incorrectly. It should be "Classified" 
Thanks!

https://carpentries-incubator.github.io/geospatial-python/07-raster-calculations/index.html

**Comment by rbavery** [comment]
woops! good find. the episodes were overhauled so that code block is now gone.
