### ISSUE TITLE
Missing images in Episode 1

### ISSUE THREAD

**Issue by bmcandr** [carpentries-incubator/geospatial-python#14]
In episode 1, the text copied below mentions figures that are not present. See the [Intro to Geospatial Concepts](https://datacarpentry.org/organization-geospatial/01-intro-raster-data/index.html) lesson for the missing images.

>A map of elevation for Harvard Forest derived from the NEON AOP LiDAR sensor is below. Elevation is represented as continuous numeric variable in this map. The legend shows the continuous range of values in the data from around 300 to 420 meters.

...

>The map above shows elevation data for the NEON Harvard Forest field site. We will be working with data from this site later in the workshop. In this map, the elevation data (a continuous variable) has been divided up into categories to yield a categorical raster.

**Comment by rbavery** [comment]
These images do show up in my browser here: https://datacarpentry.org/organization-geospatial/01-intro-raster-data/index.html

Do you not see these images at that link? What's the url you are looking at @bmcandr ?

![Selection_114](https://user-images.githubusercontent.com/22258697/93839623-6160db00-fc42-11ea-980e-4a2e622581bb.png)
![Selection_113](https://user-images.githubusercontent.com/22258697/93839625-61f97180-fc42-11ea-9d6f-989a2ae2265f.png)

**Comment by bmcandr** [comment]
Apologies for the confusing phrasing. The images do indeed show up in the Intro to Geospatial Concepts lesson, but they do not show up in Episode 1 of *this lesson*. The images you screenshotted are missing here: https://carpentries-incubator.github.io/geospatial-python/01-intro-raster-data/index.html#about-raster-data

**Comment by rbavery** [comment]
Woops, was just coming back here when I realized that! Thanks for the find, will fix.

**Comment by rbavery** [comment]
closed by https://github.com/carpentries-incubator/geospatial-python/commit/a76b445fbd0f7ff808c7b2559cb6dfff8e3bf938
