### ISSUE TITLE
Episode 6 - syntax error in first "Challenge"

### ISSUE THREAD

**Issue by bmcandr** [carpentries-incubator/geospatial-python#15]
In the first "Challenge" at the end of episode 6, there is a syntax error in the code snippet:

```python
terrain_HARV_UTM18 _valid = terrain_HARV_UTM18.where(    # error in this line
    terrain_HARV_UTM18  != terrain_HARV_UTM18.rio.nodata)
plt.figure()
terrain_HARV_UTM18_valid.plot(cmap="viridis")
plt.title("Harvard Forest Digital Terrain Model")
```

On the first line there is a space between `UTM18` and `_valid` which causes the error.

**Comment by rbavery** [comment]
thanks, will be fixed in the next pr

**Comment by rbavery** [comment]
closed by https://github.com/carpentries-incubator/geospatial-python/commit/a76b445fbd0f7ff808c7b2559cb6dfff8e3bf938
