### ISSUE TITLE
Episode 7 - Variable name error

### ISSUE THREAD

**Issue by bmcandr** [carpentries-incubator/geospatial-python#16]
In Episode 7 under "Classifying Continuous Rasters in Python", a code snippet uses the variable name `canopy_height_classes` which is never created in the episode. It appears that in the snippet below, `canopy_height_classified` was named incorrectly and should be changed to `canopy_height_classes` to fix this issue.

```python
import numpy as np

# Defines the bins for pixel values
class_bins = [canopy_HARV.min().values, 2, 10, 20, np.inf]

# Classifies the original canopy height model array
canopy_height_classified = np.digitize(canopy_HARV, class_bins)    # rename canopy_height_classified
print(type(canopy_height_classified))
```

`canopy_height_classified` is then correctly created *using* `canopy_height_classes` in the code snippet that immediately follows:

```python
import xarray
canopy_height_classified = xarray.DataArray(canopy_height_classes, coords = canopy_HARV.coords)
plt.style.use("default")
plt.figure()
canopy_height_classified.plot()
```

**Comment by rbavery** [comment]
thanks! will be fixed.

**Comment by rbavery** [comment]
closed by https://github.com/carpentries-incubator/geospatial-python/commit/a76b445fbd0f7ff808c7b2559cb6dfff8e3bf938
