### ISSUE TITLE
Episode 7 - `os` module never imported and `mkdirs` function does not exist

### ISSUE THREAD

**Issue by bmcandr** [carpentries-incubator/geospatial-python#17]
In episode 7 under "Reassigning Geospatial Metadata and Exporting a GeoTIFF", the `os` module is not imported before use. In addition, the `mkdirs` function does not exist and should be corrected to `makedirs`. This code snippet in the episode:

```python
os.mkdirs("./data/outputs/", exist_ok=True)
canopy_HARV.rio.to_raster("./data/outputs/CHM_HARV.tif")
```

Should be changed to:

```python
import os
os.makedirs("./data/outputs/", exist_ok=True)
canopy_HARV.rio.to_raster("./data/outputs/CHM_HARV.tif")
```

**Comment by rbavery** [comment]
closed by https://github.com/carpentries-incubator/geospatial-python/commit/a76b445fbd0f7ff808c7b2559cb6dfff8e3bf938
