### ISSUE TITLE
Is episode 6 necessary?

### ISSUE THREAD

**Issue by rbavery** [carpentries-incubator/geospatial-python#19]
It covers all the gotchas to pay attention to when reprojecting one dataset to another for the purposes of doing calculations between the two. The main gotcha is that they may have different extents, and clipping/masking is often needed as another step. But episode 7's `reproject_match` function will handle reprojection and masking/clipping (masking if the dataset used for the projection information is larger, clipping if it is smaller). 

This sort of makes episode 6 redundant, unless it is useful to show folks how to reproject without changing the extent of the dataset. Any opinions on this are welcome. Maybe the projection functions and concepts taught in the two episodes can be merged and made more concise?

**Comment by alex-pakalniskis** [comment]
I'm pro-concise. As an attendee, I could see how the redundancy could be more confusing than enlightening. I like your one episode proposal.

**Comment by rbavery** [comment]
Thanks for the input @alex-pakalniskis . I think I'll squash Episode 6 into a tip to reference the `reproject` function and distinguish it from `reproject_match` and that `reproject` is the better choice if you don't want the extent of the output to be masked.

**Comment by rbavery** [comment]
Addressed by https://github.com/carpentries-incubator/geospatial-python/pull/51 following https://github.com/carpentries-incubator/geospatial-python/issues/47
