### ISSUE TITLE
spelling throughout

### ISSUE THREAD

**Issue by rbavery** [carpentries-incubator/geospatial-python#21]

**Comment by amfage** [comment]
Is this still needed? I'd be happy to check through the lessons. I'm looking for something to contribute to as part of my Software Carpentry instructor checkout.

**Comment by rbavery** [comment]
Yes definitely! I'll merge any spelling fixes or other language improvements @amfage Thanks for commenting. Let me know if you have PR questions.

**Comment by MashaRudneva** [comment]
Hi, do you still have unchecked parts? I would be happy to help here :)

**Comment by rbavery** [comment]
Hi @MashaRudneva thanks for offering! Yes, episodes without a "FIXME" label could use a look through and there are certainly spelling errors or other language improvements that could be made. You can find the list of episodes here and in the _episodes folder: https://carpentries-incubator.github.io/geospatial-python/

**Comment by rbavery** [comment]
This was pretty much handled by @seanemccartney . There might be some remaining sp errors but probably not too many so closing.
