### ISSUE TITLE
Setup Instructions Clarification

### ISSUE THREAD

**Issue by darcygray** [carpentries-incubator/geospatial-python#38]
In the setup episode for this lesson (https://carpentries-incubator.github.io/geospatial-python/setup.html) Step 2 under "Setting up the workshop environment with conda" generated confusion in our workshop when we asked participants to complete setup before the lesson:

The step reads:
**2. Right-click and “Save Link As…” this link to the virtual environment file. Name it environment.yaml and save it to your geospatial-python folder. The environment.yaml contains the names of python libraries that are required to run the lesson:**

I think a screenshot is needed here, that shows this happening and then the link should be provided not as a hyperlink but as the visible .yaml "https://carpentries-incubator.github.io/geospatial-python/files/environment.yaml"

**Comment by rbavery** [comment]
Thanks for the feedback, I recall changing the link so that it is downloaded when they click it because I thought having to copy it and paste it into a file would add more overhead. was it confusing to have the file download on click? I think a screenshot or GIF is a good idea too.

**Comment by rbavery** [comment]
We include the contents of the yaml in the lesson page, provide a preferred method of installation with a single copy/paste and also still provide the "save link as" option. Foregoing the screenshot of saving the link given that is not the easiest method for newcomers and would be OS specific which might confuse. Feel free to reraise this issue if you have feedback on the current instructions @darcygray
