### ISSUE TITLE
CRS: Converting between formats

### ISSUE THREAD

**Issue by snowman2** [carpentries-incubator/geospatial-python#40]
https://carpentries-incubator.github.io/geospatial-python/03-crs/index.html

For reference for the rasterio CRS class:
https://rasterio.readthedocs.io/en/latest/api/rasterio.crs.html
```python
import rioxarray

rds = rioxarray.open_rasterio(...)
rds.rio.crs.to_epsg()
rds.rio.crs.to_wkt()
...
```

For reference for the pyproj CRS class:
https://pyproj4.github.io/pyproj/stable/examples.html#converting-crs-to-a-different-format

For reference for what to use to store CRS information:
https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems

**Comment by snowman2** [comment]
https://carpentries-incubator.github.io/geospatial-python/aio/index.html
https://carpentries-incubator.github.io/geospatial-python/05-raster-structure/

The section about `earthypy.epsg` could be updated.

**Comment by rbavery** [comment]
Awesome thanks @snowman2 I'll make this update.

**Comment by rbavery** [comment]
@snowman2 I tried to use `rgb_stack_HARV.rio.crs.to_proj4()` to print a proj4 string but got this

```python
'+init=epsg:32618'
```

Which conflicts with later lesson description that breaks down the crs attributes in a full proj4 string:

> ### UTM Proj4 String
> Our projection string for `surface_HARV` specifies the UTM projection as follows:
> 
> `'+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs'`
> 
> * **proj=utm:** the projection is UTM, UTM has several zones.
> * **zone=18:** the zone is 18
> * **datum=WGS84:** the datum is WGS84 (the datum refers to the  0,0 reference for
> the coordinate system used in the projection)
> * **units=m:** the units for the coordinates are in meters
> * **no_defs:** This attribute is nearly obsolete and [can be ignored](https://github.com/OSGeo/PROJ/issues/494).

I like the proj representation because it shows all the most important crs info in one line, whereas WKT output is a bit too busy for the novice to parse in order to understand their CRS.

```python
'PROJCS["WGS 84 / UTM zone 18N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-75],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32618"]]'
```

I think it's good that WKT is used to store crs info instead of proj (if I read the reference correctly), but I think proj is more readable and might still be valuable to show just for inspecting purposes (this is what the R lesson does, I believe for the same reason).

What do you think about keeping the lesson the way it is? Is there a way to show the full proj string with rioxarray? I'm not opposed to changing this to focus on the rioxarray attributes that can be used to get this same info, but I thought the proj string might be the quickest way to get all the attributes (projection, utm zone, linear unit, datum)

**Comment by snowman2** [comment]
The issue you are running into is this: https://github.com/mapbox/rasterio/issues/2073.

I would recommend using `pyproj.CRS` to teach about coordinate reference systems as it provides a nice summary of the CRS in the representation and allows you to navigate through the elements,

Here is how you can convert to a pyproj CRS: https://pyproj4.github.io/pyproj/stable/crs_compatibility.html#converting-from-rasterio-crs-crs-to-pyproj-crs-crs

This is what the representation of the CRS looks like with pyproj:
```python
>>> from pyproj import CRS
>>> crs = CRS("EPSG:32618")
>>> crs
<Projected CRS: EPSG:32618>
Name: WGS 84 / UTM zone 18N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 78°W and 72°W, northern hemisphere between equator and 84°N, onshore and offshore. Bahamas. Canada - Nunavut; Ontario; Quebec. Colombia. Cuba. Ecuador. Greenland. Haiti. Jamica. Panama. Turks and Caicos Islands. United States (USA). Venezuela.
- bounds: (-78.0, 0.0, -72.0, 84.0)
Coordinate Operation:
- name: UTM zone 18N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```

However, if you would prefer to continue using PROJ strings in your lessons, pyproj does give the PROJ string representation of the CRS:
```python
>>> crs.to_proj4()
'+proj=utm +zone=18 +datum=WGS84 +units=m +no_defs +type=crs'
```

**Comment by rbavery** [comment]
@snowman2 thanks so much for this tip! I think switching to using pyproj makes a lot of sense, I like how they format the CRS summary and it removes a dependency on earthpy. I'll address this later this week.

**Comment by rbavery** [comment]
@snowman2 addressed by https://github.com/carpentries-incubator/geospatial-python/pull/44 feel free to reopen if you see anything you think could be explained better.

**Comment by snowman2** [comment]
Looks great :+1:, nice work.

Here are some suggestions:

1. Use `to_epsg()`:
```python
>>> from rasterio.crs import CRS
>>> crs = CRS.from_epsg(4326)
>>> crs.epsg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CRS' object has no attribute 'epsg'
>>> crs.to_epsg()
4326
```
2. Not all CRS have EPSG codes, `to_wkt()` is a good backup for converting to `pyproj.CRS`:
```python
>>> crs_dict = {"proj": "omerc",
... "lat_0": 45.0,
... "lonc": 45.0,
... "k": 1,
... "alpha": -45.0,
... "gamma": 0.0,
... "units": "m",
... "ellps": "WGS84",
... "no_defs": True,
... }
>>> crs = CRS(crs_dict)
>>> crs.to_epsg()
```

**Comment by rbavery** [comment]
ah yikes thanks for the heads up @snowman2 .  I can mention `from_wkt()`/`to_wkt()` as a backup
