### ISSUE TITLE
use da.quantile in notebook 05

### ISSUE THREAD

**Issue by raybellwaves** [carpentries-incubator/geospatial-python#43]
Optional.

Currently there is

```
import numpy
print(numpy.percentile(surface_HARV, 25))
print(numpy.percentile(surface_HARV, 75))
```

This could be replaced with
```
surface_HARV.quantile([0.25, 0.75])
```

**Comment by rbavery** [comment]
Cool, thanks for the heads up. I might include a tip insert to reference that numpy's version of `quantile` is named `percentile` but I think it makes sense to use the xarray methods for the lesson code where possible.
