### ISSUE TITLE
Jupyter notebook or command line?

### ISSUE THREAD

**Issue by dvanic** [carpentries-incubator/geospatial-python#6]
Should we be using the Jupyter notebook for this lesson? If yes, should we refer to it at the start?

I know the R lesson doesn't directly reference RStudio, but that's probably because nearly everyone nearly always is using RStudio at the moment anyway, so perhaps that's why it isn't explicitly mentioned.

(This is more of a discussion post than a true issue)

**Comment by rbavery** [comment]
Hey @dvanic, thanks for starting this discussion. From feedback and my own teaching experience I find notebooks to be the best python teaching tool. I typically spend about 30 minutes getting people familiar with the interface and dealing with setup issues at the start of workshops. I've taught workshops using python scripts with nano/Sublime text/your favorite text editor but I received feedback from participants and workshop hosts after that notebooks were preferred in retrospect.

I'm making a to do list issue that folks can use to track what needs to be done in this repo (and the task list is open to discussion/edit). I'll put on there an item to decide on and then reference in the lesson what instructional environment should be used for the lesson.

**Comment by rbavery** [comment]
We currently reference a Starting Jupyterlab section in https://carpentries-incubator.github.io/geospatial-python/setup.html
