### ISSUE TITLE
Ep. 12 - Calculating Zonal Statistics on Rasters - NameError

### ISSUE THREAD

**Issue by seanemccartney** [carpentries-incubator/geospatial-python#69]
Error message thrown when running code. 

NameError: name 'road_canopy_zones_arr' is not defined

<img width="682" alt="Screen Shot 2021-06-15 at 1 51 09 PM" src="https://user-images.githubusercontent.com/14008923/122100198-e8fa0580-cde0-11eb-9982-41d061fca50f.png">

**Comment by rbavery** [comment]
solved by your PR, thanks!
