### ISSUE TITLE
Ep 12 - Calculating Zonal Statistics on Rasters

### ISSUE THREAD

**Issue by seanemccartney** [carpentries-incubator/geospatial-python#71]
Error message thrown when running last chunk of code in episode.

<img width="860" alt="Screen Shot 2021-06-15 at 2 08 06 PM" src="https://user-images.githubusercontent.com/14008923/122102255-3d9e8000-cde3-11eb-9636-532ad84de54c.png">

**Comment by rbavery** [comment]
Got it, I'll look into this before the session tomorrow and update the lesson.
