### ISSUE TITLE
Ep 12 - Calculating Zonal Statistics on Rasters

### ISSUE THREAD

**Issue by evanheberlein** [carpentries-incubator/geospatial-python#77]
There's a bug in the import chunk - the second imported file is actually `HARV_dtmCrop_WGS84.tif` in the data folder, not `HARV_dtmCrop_UTM18.tif `as the tutorial says.

**Comment by rbavery** [comment]
it's actually the correct file name, but this file is created in episode 6


```python
reprojected_path = "data/NEON-DS-Airborne-Remote-Sensing/HARV/DTM/HARV_dtmCrop_UTM18.tif"
terrain_HARV_UTM18.rio.to_raster(reprojected_path)
```

however I forgot to include this file in the data download link, so it means this episode is not self contained. I'll add the file to the data download so this episode can be run independently.

CC @rogerkuou

**Comment by rbavery** [comment]
just updated the dataset

**Comment by rogerkuou** [comment]
@rbavery Thanks a lot for clearing this up!
