### ISSUE TITLE
To Do List (feel free to sign up for something, add a task, and discuss)

### ISSUE THREAD

**Issue by rbavery** [carpentries-incubator/geospatial-python#8]
- [ ] Rewrite episodes 2-14 of geospatial R for python. Episodes located in `_episodes`
    - My workflow for this is to have the editing episode file and the corresponding R geospatial episode side by side, [like this one](https://datacarpentry.org/r-raster-vector-geospatial/02-raster-plot/index.html). You can see an example of how I've "translated" the first episode of the geospatial R lesson into the first geospatial Python episode:
     R version: https://datacarpentry.org/r-raster-vector-geospatial/01-raster-structure/index.html
     Python version: https://carpentries-incubator.github.io/geospatial-python/01-raster-structure/index.html
    - Feel free to heavily or lightly restructure the flow of the episodes, the text, plots, data examples etc. as you translate.
- [x] Make a Geospatial Installation Instructions Page
    - See https://github.com/carpentries-incubator/geospatial-python/issues/3, this also involves making a conda environment learners can use. Should the conda environment include jupyter lab? See next task...
- [x] Decide on what programming environment to use for the lesson and communicate this in the setup instructions.
    - see https://github.com/carpentries-incubator/geospatial-python/issues/6
- [ ] Make an abridged intro to Python lesson based on https://swcarpentry.github.io/python-novice-gapminder/
    - This is similar to how the geospatial R lesson links to [an abridged R lesson](https://datacarpentry.org/r-intro-geospatial/). Ideally this lesson is taught day one before the geospatial portion (not high priority since we  get by just using the existing python novice lessons)
- [x] change vector lessons once Geopandas 0.7.0 is released on conda-forge to reflect new use of the `pyproj.CRS` object. Details here https://twitter.com/geopandas/status/1227286762223001602

If you'd like to call dibs on an episode, you can reply here or submit a work in progress PR. I'm happy to help folks out with the workflow for contributing to open source projects if they are new to it. I'll also be contributing to more of the episodes after the holidays.

**Comment by alex-pakalniskis** [comment]
I'd be happy to help out rewriting some episodes from R to Python. 

Calling dibs on https://datacarpentry.org/r-raster-vector-geospatial/10-vector-csv-to-shapefile-in-r/index.html to start off.

This is my first contribution to an open source project so I would appreciate a bit of guidance :smile:. Once I finish pushing all edits to my forked copy, do I submit a pull request to merge the changes? 

Thanks!

**Comment by rbavery** [comment]
Thanks @alex-pakalniskis ! Yes, that's right, you can submit your pull request to the gh-pages branch of this repo. This question has also prompted me to update this contributing guidelines page, which now links to this repository and the online lesson page: https://github.com/carpentries-incubator/geospatial-python/blob/gh-pages/CONTRIBUTING.md

The section "Using Github" is a good outline to follow and https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github is a good, more advance reference that shows you how to handle issues like updating a PR that has fallen behind changes to the gh-pages branch. When you submit a PR it's also a good idea to view the changes you made as a webpage to make sure the changes render properly. To do this, run `make serve` to serve your edits locally.

Thanks for your help! Feel free to ping me in this issue if you have more questions.

**Comment by rbavery** [comment]
Hi @alex-pakalniskis just wanted to give you a heads up that I have some initial work done on the lesson you called dibs on since I had to teach part of it at JPL. I included in in an existing episode but it could be broken out into it's own episode maybe. See https://carpentries-incubator.github.io/geospatial-python/09-vector-open-shapefile/index.html there is a section called "Reading a Shapefile from a csv"
