### ISSUE TITLE
visualize optical time series from sentinel-2 lesson

### ISSUE THREAD

**Issue by rbavery** [carpentries-incubator/geospatial-python#83]
this could follow the example of https://datacarpentry.org/r-raster-vector-geospatial/12-time-series-raster/index.html  but instead use a Sentinel-2 optical time series from a previous stackstac episode. This could involve the following learning objectives:

* assembling band arrays into a single multiband array with xarray
* compute multispectral indices, either by hand or using xarray-spatial as an example https://github.com/makepath/xarray-spatial
* plot change over time at a pixel, or other summary plots. we can use hvplot + xarray for this: https://github.com/makepath/xarray-spatial

**Comment by rbavery** [comment]
other idea: netherlands crop boundaries, plotting change in spectral indices for a field over time

**Comment by rbavery** [comment]
this comment applies to this issue: https://github.com/carpentries-incubator/geospatial-python/issues/85#issuecomment-1021478181

@rogerkuou

**Comment by rbavery** [comment]
@rogerkuou @fnattino I've selected an initial area for this episode, the goal is to compute focal stats with xarray-spatial on a time series of sentinel-2 derived ndvi and see which farms have the highest average greeeness over the growing season (or something like that).

What do you two think of this initial area? I selected a spot that bordered the north of Amsterdam since globally that might be the most recognizable, but if there is an area with a more interesting story to tell through the episode that either of you know of, I'm down to change it.

![Screenshot from 2022-01-27 20-53-01](https://user-images.githubusercontent.com/22258697/151489623-ecdb76f1-c3bc-486b-ab2c-abe25c9c2868.png)

**Comment by rogerkuou** [comment]
Thanks Ryan! Looks good! I am working on a Notebook for #88 and selected almost the same area like this. I will finish the notebook and push today, we can always align in the end to make the AoI the same.

**Comment by rbavery** [comment]
closing in favor of the stackstac issue #82 , these episodes could probably one and the same
