### ISSUE TITLE
Possibly use a different, more eye catching example for single band imagery and vectors

### ISSUE THREAD

**Issue by rbavery** [carpentries-incubator/geospatial-python#85]
Feel free to comment with ideas!

oil slicks in radar imagery: https://figshare.com/articles/dataset/S1A_IW_GRDH_1SDV_20211013T064329_20211013T064354_040097_04BF7D_66FF_tiff/16916038

**Comment by rogerkuou** [comment]
Hi @rbavery I quite like the idea of S1 GRD data and the oil leak case. Here are some thoughts:

1. I think it creates a very good storyline. We can design the lesson story around pollute evaluation.
2. It's single band
3. S1 is open data, perhaps we can even try to acquire it from an open-source with STAC? If we also consider teaching down sampling data.
4. For raster/vector interaction, we can design an exercise of 1) pollution evaluation of coastline profile; 2) pollution evaluation within a certain buffer of oil rigs?
5. When expanding the course to multi-band, we can also do time-series analysis on the same vector file.

**Comment by rogerkuou** [comment]
Hi @rbavery, about the Dutch crop fields boundary data we talked about, I found the original source. It's publicly available through the Dutch government geo-info open data portal. Here is the [download page](https://service.pdok.nl/rvo/brpgewaspercelen/atom/v1_0/basisregistratie_gewaspercelen_brp.xml). You may need Google Translate's help to understand Dutch -_^.

There I downloaded the `brpgewaspercelen_voorlopig_2021.gpkg`, it's the cropfield boundary which can be put in QGIS and export as shp. 

I think we can totally forget the 4TU data I shared and start from here.

**Comment by rbavery** [comment]
this is done
