### ISSUE TITLE
[Episode 6] Replace use of Well-Known Text CRS output with `pyproj` CRS summary 

### ISSUE THREAD

**Issue by bmcandr** [carpentries-incubator/geospatial-python#94]
Episode 6 prints the CRS summary for the two datasets with `surface_HARV.rio.crs.wkt`. In Episode 5 we introduce `pyrpoj`'s `CRS()` method for printing a CRS summary for a dataset. Also, the output from this approach is easier to parse.

Unless we want to use the `wkt` approach to show another method for accessing CRS info, I recommend updating Episode 6 to use the `pyrpoj` approach.

I'm happy to make a PR for this.

**Comment by rbavery** [comment]
@bmcandr good catch, I can review that when it is ready!
