### ISSUE TITLE
Add Path Addition Recommendation?

### ISSUE THREAD

**Issue by kdottiemo** [carpentries-incubator/geospatial-python#96]
In Setup:
https://carpentries-incubator.github.io/geospatial-python/setup.html

Several times, in assisting with this and similar lessons using Anaconda, I have found that it's best to recommend that the learner check off the option "Add Anaconda to my PATH environment variable" in addition to leaving checked the "Register Anaconda as my default Python 3.x" option. It solves a lot of eventual Git Bash problems from the get-go. Would you consider adding that into the Setup content as a recommendation?

I'm not sure if this is more often a recommendation for Windows users. My latest encounter with this issue was for a Windows user though.

**Comment by rbavery** [comment]
Definitely. I think some carpentries lessons already recommend this and we should do so here, particularly for Windows OSes

**Comment by rbavery** [comment]
This is done with #106
